# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UAVPreparerProcessing
                                 A QGIS plugin
 This plugin examines height properties on a DSM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-15
        copyright            : (C) 2021 by Fredrik Lindberg
        email                : fredrikl@gvc.gu.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Fredrik Lindberg'
__date__ = '2021-03-15'
__copyright__ = '(C) 2021 by Fredrik Lindberg'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UAVPreparerProcessing class from file UAVPreparerProcessing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uav_preparer_processing import UAVPreparerProcessingPlugin
    return UAVPreparerProcessingPlugin()
